In [ ]:
import pandas as pd
import numpy as np

path = "car.csv"

df = pd.read_csv(path)
df.loc[df.groupby("Make")["MSRP"].idxmax()][["Make", "Model", "Year", "MSRP"]]

                Make                    Model  Year     MSRP
7263           Acura                      NSX  2017   156000
475       Alfa Romeo                       4C  2015    68400
11213   Aston Martin                 Vanquish  2016   320695
7982            Audi                       R8  2015   199900
720              BMW                 7 Series  2015   141200
1676         Bentley                  Azure T  2010   363000
11362        Bugatti              Veyron 16.4  2008  2065902
3934           Buick                  Enclave  2017    49625
11730       Cadillac                    XLR-V  2009   104215
3021       Chevrolet                 Corvette  2017    92395
3092        Chrysler                Crossfire  2006    49470
9957           Dodge                SRT Viper  2013   120395
539             FIAT                     500e  2015    31800
4024         Ferrari                     Enzo  2003   643330
5602            Ford                       GT  2005   149995
11859            GMC                 Yukon XL  2017    71665
5203         Genesis                      G80  2017    54550
5696          HUMMER                       H3  2009    43130
7626           Honda                    Pilot  2017    47070
4081         Hyundai                    Equus  2015    68750
7955        Infiniti                     QX80  2016    88850
6262             Kia                     K900  2016    61900
8486     Lamborghini                 Reventon  2008  1500000
8325      Land Rover              Range Rover  2016   199495
6438           Lexus                      LFA  2012   375000
7152         Lincoln                Navigator  2016    76650
4218           Lotus                   Esprit  2004    93225
5547        Maserati  GranTurismo Convertible  2015   182009
6351         Maybach                Landaulet  2012  1382750
3417           Mazda                     CX-9  2016    44015
704          McLaren              650S Spider  2015   280225
9683   Mercedes-Benz              SLR McLaren  2008   495000
6322      Mitsubishi         Lancer Evolution  2015    38995
5597          Nissan                     GT-R  2015   149990
9426      Oldsmobile               Silhouette  2004    36795
7740        Plymouth                  Prowler  2001    44625
5209         Pontiac                       G8  2009    37610
2339         Porsche               Carrera GT  2004   440000
7564     Rolls-Royce                  Phantom  2016   492425
823             Saab                      9-3  2009    51330
4897           Scion                     FR-S  2015    31090
2117          Spyker                       C8  2009   219990
11460         Subaru                      WRX  2016    39995
11694         Suzuki                      XL7  2007    31749
6932           Tesla                  Model S  2016   134500
6349          Toyota             Land Cruiser  2017    84325
7549      Volkswagen                  Phaeton  2006   101300
11631          Volvo                     XC90  2016    65700

In [ ]:
convertibles = df[df["Vehicle Style"].str.lower() == "convertible"]

convertibles.loc[convertibles.groupby("Make")["MSRP"].idxmax()][
    ["Make", "Model", "Year", "Vehicle Style", "MSRP"]
]

                Make                    Model  Year Vehicle Style     MSRP
478       Alfa Romeo                       4C  2016   Convertible    65900
11213   Aston Martin                 Vanquish  2016   Convertible   320695
7978            Audi                       R8  2015   Convertible   199600
1398             BMW                   Alpina  2003   Convertible   136900
1676         Bentley                  Azure T  2010   Convertible   363000
2345           Buick                  Cascada  2017   Convertible    37065
11730       Cadillac                    XLR-V  2009   Convertible   104215
3021       Chevrolet                 Corvette  2017   Convertible    92395
3092        Chrysler                Crossfire  2006   Convertible    49470
9147           Dodge                   Shadow  1992   Convertible     2000
34              FIAT               124 Spider  2017   Convertible    28195
10094        Ferrari             Superamerica  2005   Convertible   294080
9178            Ford             Shelby GT500  2014   Convertible    60110
8848           Honda                    S2000  2009   Convertible    37995
7828        Infiniti          Q60 Convertible  2014   Convertible    62100
1622     Lamborghini                Aventador  2014   Convertible   548800
9042           Lexus                   SC 430  2010   Convertible    68405
3919           Lotus                    Elise  2011   Convertible    57950
5547        Maserati  GranTurismo Convertible  2015   Convertible   182009
6351         Maybach                Landaulet  2012   Convertible  1382750
7120           Mazda               MX-5 Miata  2015   Convertible    32655
704          McLaren              650S Spider  2015   Convertible   280225
9683   Mercedes-Benz              SLR McLaren  2008   Convertible   495000
3771      Mitsubishi           Eclipse Spyder  2010   Convertible    32599
317           Nissan                     370Z  2015   Convertible    49400
3327      Oldsmobile          Cutlass Supreme  1995   Convertible     2000
7740        Plymouth                  Prowler  2001   Convertible    44625
5193         Pontiac                       G6  2009   Convertible    32300
2339         Porsche               Carrera GT  2004   Convertible   440000
7558     Rolls-Royce   Phantom Drophead Coupe  2016   Convertible   492000
823             Saab                      9-3  2009   Convertible    51330
2117          Spyker                       C8  2009   Convertible   219990
2238          Toyota             Camry Solara  2008   Convertible    30710
4029      Volkswagen                      Eos  2015   Convertible    42745
2115           Volvo                      C70  2013   Convertible    41200

In [ ]:
automatic_cars = df[df["Transmission Type"].str.upper() == "AUTOMATIC"]

automatic_cars

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
19,Audi,100,1992,regular unleaded,172.0,6.0,AUTOMATIC,all wheel drive,4.0,Luxury,Midsize,Wagon,20,16,3105,2000
23,Audi,100,1993,regular unleaded,172.0,6.0,AUTOMATIC,all wheel drive,4.0,Luxury,Midsize,Wagon,20,16,3105,2000
27,Audi,100,1994,regular unleaded,172.0,6.0,AUTOMATIC,front wheel drive,4.0,Luxury,Midsize,Wagon,21,16,3105,2000
30,Audi,100,1994,regular unleaded,172.0,6.0,AUTOMATIC,front wheel drive,4.0,Luxury,Midsize,Sedan,22,16,3105,2000
31,Audi,100,1994,regular unleaded,172.0,6.0,AUTOMATIC,all wheel drive,4.0,Luxury,Midsize,Wagon,21,16,3105,2000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11909,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,46120
11910,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,56670
11911,Acura,ZDX,2012,premium unleaded (required),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50620
11912,Acura,ZDX,2013,premium unleaded (recommended),300.0,6.0,AUTOMATIC,all wheel drive,4.0,"Crossover,Hatchback,Luxury",Midsize,4dr Hatchback,23,16,204,50920
11913,Lincoln,Zephyr,2006,regular unleaded,221.0,6.0,AUTOMATIC,front wheel drive,4.0,Luxury,Midsize,Sedan,26,17,61,28995

In [ ]:
premium_cars = df[
    df["Engine Fuel Type"].str.lower().str.contains("premium", na=False)
]

premium_cars[["Make", "Model", "Year", "Engine Fuel Type", "MSRP"]]

        Make       Model  Year                Engine Fuel Type   MSRP
0        BMW  1 Series M  2011     premium unleaded (required)  46135
1        BMW    1 Series  2011     premium unleaded (required)  40650
2        BMW    1 Series  2011     premium unleaded (required)  36350
3        BMW    1 Series  2011     premium unleaded (required)  29450
4        BMW    1 Series  2011     premium unleaded (required)  34500
...      ...         ...   ...                             ...    ...
11908  Acura         ZDX  2011     premium unleaded (required)  50520
11909  Acura         ZDX  2012     premium unleaded (required)  46120
11910  Acura         ZDX  2012     premium unleaded (required)  56670
11911  Acura         ZDX  2012     premium unleaded (required)  50620
11912  Acura         ZDX  2013  premium unleaded (recommended)  50920

[3612 rows x 5 columns]

In [ ]:
df.groupby("Make")["MSRP"].mean().sort_values(ascending=False)

Make
Bugatti          1.757224e+06
Maybach          5.462219e+05
Rolls-Royce      3.511306e+05
Lamborghini      3.315673e+05
Bentley          2.471693e+05
McLaren          2.398050e+05
Ferrari          2.382188e+05
Spyker           2.133233e+05
Aston Martin     1.979104e+05
Maserati         1.142077e+05
Porsche          1.016224e+05
Tesla            8.525556e+04
Mercedes-Benz    7.147623e+04
Lotus            6.918828e+04
Land Rover       6.782322e+04
Alfa Romeo       6.160000e+04
BMW              6.154676e+04
Cadillac         5.623132e+04
Audi             5.345211e+04
Lexus            4.754907e+04
Genesis          4.661667e+04
Lincoln          4.283983e+04
Infiniti         4.239421e+04
HUMMER           3.646441e+04
Acura            3.488759e+04
GMC              3.049330e+04
Toyota           2.903002e+04
Nissan           2.858343e+04
Volvo            2.854116e+04
Chevrolet        2.835039e+04
Buick            2.820661e+04
Volkswagen       2.810238e+04
Saab             2.741350e+04
Ford             2.739927e+04
Chrysler         2.672296e+04
Honda            2.667434e+04
Kia              2.531017e+04
Subaru           2.482750e+04
Hyundai          2.459704e+04
FIAT             2.267024e+04
Dodge            2.239006e+04
Mitsubishi       2.124054e+04
Mazda            2.003938e+04
Scion            1.993250e+04
Pontiac          1.932155e+04
Suzuki           1.790721e+04
Oldsmobile       1.154254e+04
Plymouth         3.122902e+03
Name: MSRP, dtype: float64