<a href="https://colab.research.google.com/github/SnehaPandit10/da-ml-assignment/blob/main/courses.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
code=['c1','c2','c3','c4','c5']
courses = ['PGDBDA','PGDAI','PGDMC','PGDCSF','PGDGI']
lang=['python','python','java','c++','rprog']
df = pd.DataFrame({'code':code,'courses':courses,'languages':lang})
df

  code courses languages
0   c1  PGDBDA    python
1   c2   PGDAI    python
2   c3   PGDMC      java
3   c4  PGDCSF       c++
4   c5   PGDGI     rprog

In [ ]:
from sklearn.preprocessing import LabelEncoder
l = LabelEncoder()
df['lang_encoded'] = l.fit_transform(df['languages'])
df

  code courses languages  lang_encoded
0   c1  PGDBDA    python             2
1   c2   PGDAI    python             2
2   c3   PGDMC      java             1
3   c4  PGDCSF       c++             0
4   c5   PGDGI     rprog             3

In [ ]:
data = ['PGDBDA','PGDAI','PGDMC','PGDCSF','PGDGI']
l.fit_transform(data)
l.classes_
e_data = l.transform(data)

In [ ]:
d = pd.DataFrame({})
d['course_encoded'] = e_data
d

   course_encoded
0               1
1               0
2               4
3               2
4               3

In [ ]:
from sklearn.preprocessing import OneHotEncoder
o = OneHotEncoder(sparse_output=False)
o_c = o.fit_transform(df[['courses']])
encoded_df = pd.DataFrame(o_c, columns=o.get_feature_names_out(['courses']))
d = pd.concat([d,encoded_df],axis=1)
d

,course_encoded,courses_PGDAI,courses_PGDBDA,courses_PGDCSF,courses_PGDGI,courses_PGDMC
0,1,0.0,1.0,0.0,0.0,0.0
1,0,1.0,0.0,0.0,0.0,0.0
2,4,0.0,0.0,0.0,0.0,1.0
3,2,0.0,0.0,1.0,0.0,0.0
4,3,0.0,0.0,0.0,1.0,0.0